### ISSUE TITLE
Why is it not working for me? :(

### ISSUE THREAD

**Issue by abhisheksoni27** [notwaldorf/to_emoji#1]
It hasn't tweeted for the past thirty minutes. :thinking:

**Comment by notwaldorf** [comment]
![screen shot 2017-06-12 at 12 15 45 pm](https://user-images.githubusercontent.com/1369170/27050873-e93ce0bc-4f68-11e7-8d82-10e940438667.png)

Twitter rate limits their API, and the bot got too popular too fast, so it's throttled

**Comment by abhisheksoni27** [comment]
That sucks.Is there no way you could surpass it?

**Comment by notwaldorf** [comment]
lol no, that's the whole point of a rate limit. You can read about it here: https://dev.twitter.com/rest/public/rate-limiting

**Comment by abhisheksoni27** [comment]
I did. Maybe you could contact Twitter and ask them to understand this use case? What if they cut the bot some slack? Idk. This rate limit just makes the bot seem sassy.

**Comment by notwaldorf** [comment]
I'm sorry, there's literally nothing I can do about it.

**Comment by notwaldorf** [comment]
For the record, it's  back up now. Until it gets limited again 😅

**Comment by abhisheksoni27** [comment]
Thanks. :smile:
